### PR TITLE
adds github action to automate client library generation

### PR DESCRIPTION
**Pull request by tgallant**
see https://github.com/lilt/lilt-python/pull/18 and https://github.com/lilt/lilt-node/pull/5

### CODE REVIEW

**Review by tingley — APPROVED** [review]

**Comment by tgallant** [comment]
@tingley could you list the options you used for the most recent codegen? i need to update this to use the actual values

**Comment by tingley** [comment]
@tgallant I ran 
```
openapi-generator-cli generate -i ../front/doc/public-http-api-swagger.yaml  -g java  --git-host github.com  --git-user-id lilt  --package-name lilt  -o . --skip-validate-spec -c config.json 
```

where `config.json` contains:

```json
{
    "modelPackage" : "com.lilt.client.model",
    "apiPackage" : "com.lilt.client.api"
}
```

One annoying thing is that this will try to modify the `.gitignore` file.

**Comment by tgallant** [comment]
we can ignore regenerating certain files

https://openapi-generator.tech/docs/faq-extending/#how-do-i-skip-files-during-code-generation

should we add `.gitignore` to `.openapi-generator-ignore`? anything else that should be left as is?

**Comment by tingley** [comment]
I've removed a bunch of other build files and for now it's easier if we don't regenerate them:
* git_push.sh
* gradlew
* gradle.properties
* build.gradle
* settings.properties
* gradlew.bat
* build.sbt

**Pull request merged**
